### ISSUE TITLE
pou-lua and pou-search

### ISSUE THREAD

**Issue by DaniElectra** [H401217/wss-lua#1]
Hello! I can't find any contact information, so I'll use this issue to contact you.

Earlier this year I found your repos called `pou-lua` and `pou-search`, where you had reverse-engineered the Pou API used by the app for online accounts. Since then, I've made my own research on Pou's API and Pou vs Pou. But one day when I went to search your repos, they weren't there anymore.

I would like to ask you if there's any chance you can publish the source code of those repos back. Alternatively, at least I would like to know your knowledge on Pou's avatar data `minInfo`.

Greetings

*btw, we can speak spanish if you want to*

**Comment by H401217** [comment]
Hello!
**I** removed `pou-search` repository due to a request (via reddit by an "r/pou" mod) that said that it would violate copyright (like other "Pou RTX" apps [made by other people] that were also taken down due to trademark infringement)
After doing that, I also decided to remove (**by myself**) `pou-lua`.
I still have the source of the repos.

About the "minInfo" (aka "minI") I see that fields like "ouf", "nek", "hat", etc; are probably concatenated IDs, I still don't know much about this.
These are some of the fields available in the "minInfo" object:
```
sz=Size of pou
ob=Obesity of pou
bCo=Body Color
eCo=Eye Color
ouf=Outfit (t-shirt,shirt,etc)
ela=Eye lashes 
esh=Eye shadow color
nek=Neck accessory
hat=Hat
stk=Sticker (could be flags, zodiac signs, etc)
sho=Shoes
```
(there are more fields)

Also, the "hP" field located in the "site/login" response is to check if the account has a password (yes, you can also decide to not put a password to your account temporally after creating it) , and that explains why does "sentNewPassword" bool appears in "site/check_email" response (it indicates that a new password was sent to your email because your account didn't have a password, it's shown when you login again to your account)

And, the "notification/claim" endpoint serves for claiming notifications, **and these notifications serve the purpose of giving an award to the player's pou** (for example, coins). These notifications were available in Pou events (for example, christmas) in which you needed to save your account progress to get the notifications and claim them.

**Comment by DaniElectra** [comment]
Thank you so much for answering! I wasn't aware of the takedown request, now I understand what happened.

Also thank you for the additional information about claiming notifications and the account password
